---
- hosts: wg
  become: true

  tasks:

  - name: Install fail2ban service
    apt: name=fail2ban state=latest

  - name: copy
    shell: cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local

  - name: replace IP
    shell: sed -i 's/#ignoreip =/ignoreip = 163...165 136...180/' /etc/fail2ban/jail.local

  - name: replace bantime
    shell: sed -i 's/bantime  = 10m/bantime  = 60m/' /etc/fail2ban/jail.local

  - name: Start fail2ban and Enable
    service: name=fail2ban state=started enabled=yes

