---
- hosts: wg
  become: true

  tasks:

  - name: Install fail2ban service
    apt: name=fail2ban state=latest


  - name: Start fail2ban and Enable
    service: name=fail2ban state=started enabled=yes
