---
- hosts: wg
  become: true

  tasks:

  - name: Download WG scripts
    uri:
      url: "https://raw.githubusercontent.com/mihonukr/scripts/master/wireguard-install.sh"
      dest: /root
      
  - name: Changing chmod adding "+x"
    file: dest=/root/wireguard-install.sh mode=+x
