---
- hosts: wg
  become: true

  tasks:

  - name: Download WG scripts
    uri:
      url: "https://raw.githubusercontent.com/angristan/wireguard-install/master/wireguard-install.sh"
      dest: /root
